gameengine.js
goblin.js
ground.js
index.html
knight.js
sceneManager.js
wizard.js

-added simple check for bottom collision detection for when jumping into a block from bottom (does not handle from side though)
-Added 3 platforms in a prototype level for proof of concept
-Place all enemy animations arbitrarily in the prototype lvl to show them off. (you cant interact with them)

Prototype Demo + Bonk Collision

---

engine/gameengine.js
engine/sceneManager.js
entity/enemy/mushroom.js
entity/player/knight.js
entity/projectile/arrow.js

Split the entities array into multiple arrays to separate the update and provide layering effect when drawing.
Also, updated all files that utilized the original entities array thus far.

Created Layers

---

engine/gui/textbox.js
engine/sceneManager.js
entity/level/door.js
entity/level/levels.js
entity/level/sign.js
index.html
util.js

last changes for minimum deliverable meeting with professor
-updated textbox for scene manager

Ken (Minimum Deliverable)

---

engine/gui/textbox.js
engine/sceneManager.js
entity/level/levels.js

-title screen text boxes and sfx
-bigger text
-easier to read signs

Ken (Improves textboxes and title screen)

---

engine/sceneManager.js
entity/level/levels.js
util.js

-was missing some controls on title screen
-added kill quota per level on screen
-updated some signs
-put an npc on each level we have so far
-some new level secrets :)

Updated titlescreen + kill quota on levels

---

entity/level/diamond.js

diamond no longer gets stuck to wall when spawning next to one.

diamond spawn fix

---

entity/level/levels.js

-Lots of new puzzles and platforming parts on each level
-more chests found on each level
-most changes are on level 1-3 to use up all the empty space
-1 secret room on each floor!

Major Level Overhaul

---

engine/gui/textbox.js
engine/sceneManager.js
entity/level/door.js
entity/level/npc.js
entity/level/shop.js

-fixed bug where textboxes of the shop overlap if multiple on the same level
-custom maxed messages for upgrades
-increased reading time
-restart game resets the clock

Shop fix and more text messages

---

engine/gameengine.js
engine/sceneManager.js
entity/level/levels.js

Modified location in which the knight is loaded in the level, as well removing all entities from the level that needs

Modified level load

---

entity/level/levels.js

-better indicators with torches for the path you should go
-ground put instead of bricks in some places
-changed bottom right obelisk so u need to activate the top obelisk to get to. Put more chests in there since it is a puzzle

Level 3 update

---

entity/projectile/arrow.js

-if player team check only enemy list
-if enemy team check only player list

Small arrow optimization

---

entity/enemy/wizard.js
entity/level/levels.js
entity/projectile/enemy_projectile.js

-implemented the beam phase of the wizard
-wizard in beam phase shoots multiple wind beam projectiles stacked together
-wizard has a tracking boolean in update and when it is set it will track the player vertically and also change its direction accordingly
-modified boss level shortcut in debug room to be closer up
-modified flyingeyeprojectile so that there is a field checked if it can be destroyed or not. Did this because I want the wizard windball that extends from this to be indestructible.
-made arrow rain arrow amount related to the phase of the wizard

Initial Wizard Beam phase and tracking + arrow rain phases

---

engine/gui/textbox.js
engine/sceneManager.js
entity/level/levels.js
entity/level/npc.js
index.html

-shopkeeper npc will have a textbox when the player approaches. You can set the text through the levels json. If you dont then it will have a default text message.
-updated level 1 to have npc talk to player at the start
-I put some dialouge down for every npc on the map so far

Shopkeeper NPC Textboxes

---

engine/sceneManager.js
entity/level/levels.js

-fixed a bug where the level select was still clickable ion title even if it was hidden after clicking it
-fixed some grammar in npc dialouge

turn off level select button in title

---

engine/gameengine.js
engine/gui/textbox.js
engine/sceneManager.js
entity/enemy/demonslime.js
entity/enemy/wizard.js
entity/level/levels.js
entity/level/npc.js

lots of changes in regards to the final boss. Read all the commits for more info.

Ken (Final Boss Overhaul)

---

engine/sceneManager.js
entity/level/levels.js
entity/level/tiles.js

- Moving platforms, repeat and reverse given direction and distances
- A later update will be coming soon to address fall physics and moving left and right with the platform

initial moving platform update

---

entity/abstractentity.js
entity/level/tiles.js
entity/player/abstractplayer.js

Allow players and enemies to be influenced by platforms.

Create platform physics

---

engine/sceneManager.js
entity/level/levels.js
index.html

-updated controls with the new shop update
-updated signs, index and controlbox
-repos control box

Updated for the new shop controls

---

entity/player/knight.js

-like how the bow can switch direction with mouse you can do the same thing with the bow by pressing the opposite direction

QoL: Switch bow direction with keyboard press

---

entity/enemy/demonslime.js
entity/projectile/enemy_projectile.js

-can spawn a blue projectile that cannot be destroyed (30% chance of spawn)
-undestroyable projectiles will also destroy your arrow
-fixed the spawn of slimes with an offset. Before they just spawned all in the same place giving the appearence of just one slime spawn
-hard phase can do demon slash or demon breath

Buffed Demon Shoot

---

engine/sceneManager.js
entity/level/levels.js
entity/player/knight.js
util.js

-altered some platforms on levels
-attack qol

Ken (QoL: platforms + attacks)
